baseURL = 'https://paranoiaoops.github.io/myLog'
defaultContentLanguage = "ja"
languageCode = 'ja'
hasCKLanguage = true
title = '日記｜備忘録｜雑記'
theme = "hugo-clarity"

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
